### ISSUE TITLE
TypeError: Cannot read property 'zip' of undefined

### ISSUE THREAD

**Issue by maccyber** [telemark/tfk-saksbehandling-skoleskyss#10]
```
prepareItem: prepares item
lookupDSF: starts
lookupDSF: lookup finished
lookupDSF: RESULT missing from data
{ MESSAGE: 
   { CODE: '1',
     SUMMARY: 'Feil: Ingen funnet med angitt identifikasjon. Søket er begrenset på disse kommunenr/fylkesnr: 08.' } }
checkNSBTransport
checkNSBTransport: School is in Telemark
/srv/ws/tfk-saksbehandling/node_modules/tfk-saksbehandling-skoleskyss/lib/checkNSBTransport.js:14
    if (item.registeredAddress.zip !== '') {
                              ^
TypeError: Cannot read property 'zip' of undefined
    at Thru.transformer (/srv/ws/tfk-saksbehandling/node_modules/tfk-saksbehandling-skoleskyss/lib/checkNSBTransport.js:14:31)
    at Thru._transform (/srv/ws/tfk-saksbehandling/node_modules/tfk-saksbehandling-skoleskyss/node_modules/thru/index.js:22:10)
    at Thru.Transform._read (_stream_transform.js:167:10)
    at Thru.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:291:12)
    at writeOrBuffer (_stream_writable.js:277:5)
    at Thru.Writable.write (_stream_writable.js:206:11)
    at Thru.ondata (_stream_readable.js:522:20)
    at emitOne (events.js:77:13)
    at Thru.emit (events.js:169:7)
```

**Comment by zrrrzzt** [comment]
Hovedproblemet her er at den feiler på oppslaget mot dsf, så den skal egentlig bryte alt uansett.

Frem til jeg er tilbake fra ferie @maccyber foreslår jeg at du tar en manuell utsjekk av søknaden dette gjelder.
