### ISSUE TITLE
Feiler ved bruk av skråstrek (/)

### ISSUE THREAD

**Issue by maccyber** [telemark/tfk-saksbehandling-skoleskyss#5]
_From @maccyber on June 22, 2015 15:16_

Feiler ved bruk av skråstrek i folkeregistrertAdresseAdresse og alternativAdresseAdresse med

```
geocodeFolkeregistrertAdresse: starts
/srv/ws/tfk-saksbehandling/node_modules/tfk-saksbehandling-skoleskyss/lib/geocodeAddress.js:23
      return callback(null, json.results[0]);
                                        ^
TypeError: Cannot read property '0' of undefined
    at IncomingMessage.<anonymous> (/srv/ws/tfk-saksbehandling/node_modules/tfk-saksbehandling-skoleskyss/lib/geocodeAddress.js:23:41)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:892:12)
    at doNTCallback2 (node.js:430:9)
    at process._tickCallback (node.js:344:17)
```

_Copied from original issue: telemark/tfk-saksbehandling#1_

**Comment by maccyber** [comment]
_From @zrrrzzt on June 22, 2015 16:9_

Flytter du denne til tfk-saksbehandling-skoleskyss
